<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CarModel;

class CarModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CarModel::insert([
            [
                'id' => 1,
                'name' => 'Compass',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 2,
                'name' => 'e-tron',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 3,
                'name' => 'Escape',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 4,
                'name' => 'Expedition',
                'division_id' => 6,
                'specialist_id' => 4,
            ],
            [
                'id' => 5,
                'name' => 'A6 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 6,
                'name' => 'Q7 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 7,
                'name' => 'SQ7 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 8,
                'name' => 'A3 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 9,
                'name' => 'Q8 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 10,
                'name' => 'RS Q8 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 11,
                'name' => 'SQ8 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 12,
                'name' => 'RS 3 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 13,
                'name' => 'S3 Quattro',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 14,
                'name' => 'Jetta',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 15,
                'name' => 'Taos',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 16,
                'name' => 'Golf R',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 17,
                'name' => 'Tiguan',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 18,
                'name' => 'Pacifica',
                'division_id' => 3,
                'specialist_id' => null,
            ],
            [
                'id' => 19,
                'name' => 'Pacifica Hybrid',
                'division_id' => 3,
                'specialist_id' => null,
            ],
            [
                'id' => 20,
                'name' => 'Voyager',
                'division_id' => 3,
                'specialist_id' => null,
            ],
            [
                'id' => 21,
                'name' => 'Ram 1500 Crew Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 22,
                'name' => 'Ram 1500 Mega Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 23,
                'name' => 'Ram 2500 Crew Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 24,
                'name' => 'Ram 2500 Mega Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 25,
                'name' => 'Ram 2500 Regular Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 26,
                'name' => 'Ram 3500 Crew Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 27,
                'name' => 'Ram 3500 Mega Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 28,
                'name' => 'Ram 3500 Regular Cab',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 29,
                'name' => 'Charger',
                'division_id' => 5,
                'specialist_id' => 4,
            ],
            [
                'id' => 30,
                'name' => 'Durango',
                'division_id' => 5,
                'specialist_id' => 6,
            ],
            [
                'id' => 31,
                'name' => 'Hornet',
                'division_id' => 5,
                'specialist_id' => 4,
            ],
            [
                'id' => 32,
                'name' => 'Cherokee',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 33,
                'name' => 'Grand Cherokee 2 Row',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 34,
                'name' => 'Grand Cherokee L 3 Row',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 35,
                'name' => 'Golf GTI',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 36,
                'name' => 'Gladiator',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 37,
                'name' => 'Grand Wagoneer',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 38,
                'name' => 'Grand Wagoneer L',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 39,
                'name' => 'Wagoneer',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 40,
                'name' => 'Wagoneer L',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 41,
                'name' => 'Wrangler 2 Door',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 42,
                'name' => 'Wrangler 4 Door',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 43,
                'name' => 'Camaro',
                'division_id' => 2,
                'specialist_id' => null,
            ],
            [
                'id' => 44,
                'name' => 'Malibu',
                'division_id' => 2,
                'specialist_id' => null,
            ],
            [
                'id' => 45,
                'name' => 'Bronco',
                'division_id' => 6,
                'specialist_id' => null,
            ],
            [
                'id' => 46,
                'name' => 'Bronco Sport',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 47,
                'name' => 'Edge',
                'division_id' => 6,
                'specialist_id' => 5,
            ],
            [
                'id' => 48,
                'name' => 'Escape',
                'division_id' => 6,
                'specialist_id' => 5,
            ],
            [
                'id' => 49,
                'name' => 'Expedition',
                'division_id' => 6,
                'specialist_id' => 5,
            ],
            [
                'id' => 50,
                'name' => 'Explorer',
                'division_id' => 6,
                'specialist_id' => 5,
            ],
            [
                'id' => 51,
                'name' => 'F-150 Regular Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 52,
                'name' => 'F-150 Super Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 53,
                'name' => 'F-150 Super Crew',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 54,
                'name' => 'F-250 SRW Regular Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 55,
                'name' => 'F-250 SRW Super Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 56,
                'name' => 'F-250 SRW Super Crew',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 57,
                'name' => 'F-350 SRW Regular Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 58,
                'name' => 'F-350 SRW Super Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 59,
                'name' => 'F-350 SRW Super Crew',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 60,
                'name' => 'F-350 DRW Regular Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 61,
                'name' => 'F-350 DRW Super Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 62,
                'name' => 'F-350 DRW Super Crew',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 63,
                'name' => 'F-450 DRW Regular Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 64,
                'name' => 'F-450 DRW Crew Cab',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 65,
                'name' => 'Maverick',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 66,
                'name' => 'Mustang',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 67,
                'name' => 'Mustang Mach-E',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 68,
                'name' => 'Ranger',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 69,
                'name' => 'Shelby GT',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 70,
                'name' => 'Transit Cargo Van',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 71,
                'name' => 'Transit Crew Van',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 72,
                'name' => 'Transit Passenger Van',
                'division_id' => 6,
                'specialist_id' => 3,
            ],
            [
                'id' => 73,
                'name' => 'Aviator',
                'division_id' => 12,
                'specialist_id' => null,
            ],
            [
                'id' => 74,
                'name' => 'Corsair',
                'division_id' => 12,
                'specialist_id' => null,
            ],
            [
                'id' => 75,
                'name' => 'Navigator',
                'division_id' => 12,
                'specialist_id' => null,
            ],
            [
                'id' => 76,
                'name' => 'Navigator L',
                'division_id' => 12,
                'specialist_id' => null,
            ],
            [
                'id' => 77,
                'name' => 'Accord',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 78,
                'name' => 'Civic',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 79,
                'name' => 'CR-V',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 80,
                'name' => 'CR-Z',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 81,
                'name' => 'HR-V',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 82,
                'name' => 'Odyssey',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 83,
                'name' => 'Passport',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 84,
                'name' => 'Pilot',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 85,
                'name' => 'Q60',
                'division_id' => 9,
                'specialist_id' => null,
            ],
            [
                'id' => 86,
                'name' => 'QX50',
                'division_id' => 9,
                'specialist_id' => null,
            ],
            [
                'id' => 87,
                'name' => 'Altima',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 88,
                'name' => 'Altima L',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 89,
                'name' => 'Altima L',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 90,
                'name' => 'Frontier',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 91,
                'name' => 'Leaf',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 92,
                'name' => 'Rogue',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 93,
                'name' => 'Murano',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 94,
                'name' => 'Pathfinder',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 95,
                'name' => 'Versa',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 96,
                'name' => 'Z Proto Spec',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 97,
                'name' => 'C-HR',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 98,
                'name' => 'Camry',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 99,
                'name' => '4Runner',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 100,
                'name' => 'Tacoma',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 101,
                'name' => 'Corolla',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 102,
                'name' => 'Highlander',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 103,
                'name' => 'RAV4',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 104,
                'name' => 'Sienna',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 105,
                'name' => 'Atlas',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 106,
                'name' => 'Atlas Cross Sport',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 107,
                'name' => 'ID.4',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            [
                'id' => 108,
                'name' => 'Model Not Listed',
                'division_id' => 1,
                'specialist_id' => null,
            ],
            [
                'id' => 109,
                'name' => 'Model Not Listed',
                'division_id' => 2,
                'specialist_id' => null,
            ],
            [
                'id' => 110,
                'name' => 'Model Not Listed',
                'division_id' => 3,
                'specialist_id' => null,
            ],
            [
                'id' => 111,
                'name' => 'Model Not Listed',
                'division_id' => 4,
                'specialist_id' => null,
            ],
            [
                'id' => 112,
                'name' => 'Model Not Listed',
                'division_id' => 5,
                'specialist_id' => null,
            ],
            [
                'id' => 113,
                'name' => 'Model Not Listed',
                'division_id' => 6,
                'specialist_id' => null,
            ],
            [
                'id' => 114,
                'name' => 'Tri Glide Ultra',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 115,
                'name' => 'Model Not Listed',
                'division_id' => 8,
                'specialist_id' => null,
            ],
            [
                'id' => 116,
                'name' => 'Model Not Listed',
                'division_id' => 9,
                'specialist_id' => null,
            ],
            [
                'id' => 117,
                'name' => 'Model Not Listed',
                'division_id' => 10,
                'specialist_id' => null,
            ],
            [
                'id' => 118,
                'name' => 'Model Not Listed',
                'division_id' => 11,
                'specialist_id' => null,
            ],
            [
                'id' => 119,
                'name' => 'Model Not Listed',
                'division_id' => 12,
                'specialist_id' => null,
            ],
            [
                'id' => 120,
                'name' => 'Model Not Listed',
                'division_id' => 13,
                'specialist_id' => null,
            ],
            [
                'id' => 121,
                'name' => 'Model Not Listed',
                'division_id' => 14,
                'specialist_id' => null,
            ],
            [
                'id' => 122,
                'name' => 'Model Not Listed',
                'division_id' => 15,
                'specialist_id' => null,
            ],
            [
                'id' => 123,
                'name' => 'Model Not Listed',
                'division_id' => 16,
                'specialist_id' => null,
            ],
            //Harley-Davidson
            [
                'id' => 124,
                'name' => 'Breakout',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 125,
                'name' => 'CVO Pan America',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 126,
                'name' => 'CVO Road Glide',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 127,
                'name' => 'CVO Road Glide ST',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 128,
                'name' => 'CVO Street Glide',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 129,
                'name' => 'Fat Boy',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 130,
                'name' => 'Freewheeler',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 131,
                'name' => 'Heritage Classic',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 132,
                'name' => 'Low Rider S',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 133,
                'name' => 'Low Rider ST',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 134,
                'name' => 'Nightster',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 135,
                'name' => 'Nightster Special',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 136,
                'name' => 'Pan America Special',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 137,
                'name' => 'Pan America ST',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 138,
                'name' => 'Road Glide',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 139,
                'name' => 'Road Glide 3',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 140,
                'name' => 'Road King Special',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 141,
                'name' => 'Sportster S',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 142,
                'name' => 'Street Bob',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 143,
                'name' => 'Street Glide',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 144,
                'name' => 'Street Glide Ultra',
                'division_id' => 7,
                'specialist_id' => 0,
            ],
            [
                'id' => 145,
                'name' => 'Model Not Listed',
                'division_id' => 7,
                'specialist_id' => null,
            ],
        ]);
    }
}
