<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ticket;

class TicketSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Ticket::insert([
            [
                "id" => 1,
                "email" => "test@militarycars.com",
                "specialist_id" => 1,
                "task_id" => 1,
                "year" => "2026",
                "division_id" => 1,
                "model_id" => 1,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "unresolved",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "email" => "test2@militarycars.com",
                "specialist_id" => 1,
                "task_id" => 2,
                "year" => "2026",
                "division_id" => 2,
                "model_id" => 2,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "in_progress",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "email" => "test3@militarycars.com",
                "specialist_id" => 1,
                "task_id" => 3,
                "year" => "2026",
                "division_id" => 3,
                "model_id" => 3,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "escalated",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "email" => "test4@militarycars.com",
                "specialist_id" => 1,
                "task_id" => 4,
                "year" => "2026",
                "division_id" => 4,
                "model_id" => 4,
                "misc" => "4x4",
                "info_type" => "customer",
                "info_number" => "9102691234",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "completed",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "email" => "test5@militarycars.com",
                "specialist_id" => 2,
                "task_id" => 1,
                "year" => "2026",
                "division_id" => 1,
                "model_id" => 1,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "unresolved",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "email" => "test6@militarycars.com",
                "specialist_id" => 2,
                "task_id" => 2,
                "year" => "2026",
                "division_id" => 2,
                "model_id" => 2,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "in_progress",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "email" => "test7@militarycars.com",
                "specialist_id" => 2,
                "task_id" => 3,
                "year" => "2026",
                "division_id" => 3,
                "model_id" => 3,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "escalated",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "email" => "test8@militarycars.com",
                "specialist_id" => 2,
                "task_id" => 4,
                "year" => "2026",
                "division_id" => 4,
                "model_id" => 4,
                "misc" => "4x4",
                "info_type" => "customer",
                "info_number" => "9102691234",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "completed",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "email" => "test9@militarycars.com",
                "specialist_id" => 3,
                "task_id" => 1,
                "year" => "2026",
                "division_id" => 1,
                "model_id" => 1,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "unresolved",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 10,
                "email" => "test10@militarycars.com",
                "specialist_id" => 3,
                "task_id" => 2,
                "year" => "2026",
                "division_id" => 2,
                "model_id" => 2,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "in_progress",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 11,
                "email" => "test11@militarycars.com",
                "specialist_id" => 3,
                "task_id" => 3,
                "year" => "2026",
                "division_id" => 3,
                "model_id" => 3,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "escalated",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 12,
                "email" => "test12@militarycars.com",
                "specialist_id" => 3,
                "task_id" => 4,
                "year" => "2026",
                "division_id" => 4,
                "model_id" => 4,
                "misc" => "4x4",
                "info_type" => "customer",
                "info_number" => "9102691234",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "completed",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 13,
                "email" => "test13@militarycars.com",
                "specialist_id" => 4,
                "task_id" => 1,
                "year" => "2026",
                "division_id" => 1,
                "model_id" => 1,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "unresolved",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 14,
                "email" => "test14@militarycars.com",
                "specialist_id" => 4,
                "task_id" => 2,
                "year" => "2026",
                "division_id" => 2,
                "model_id" => 2,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "in_progress",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 15,
                "email" => "test15@militarycars.com",
                "specialist_id" => 4,
                "task_id" => 3,
                "year" => "2026",
                "division_id" => 3,
                "model_id" => 3,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "escalated",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 16,
                "email" => "test16@militarycars.com",
                "specialist_id" => 4,
                "task_id" => 4,
                "year" => "2026",
                "division_id" => 4,
                "model_id" => 4,
                "misc" => "4x4",
                "info_type" => "customer",
                "info_number" => "9102691234",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "completed",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 17,
                "email" => "test17@militarycars.com",
                "specialist_id" => 5,
                "task_id" => 1,
                "year" => "2026",
                "division_id" => 1,
                "model_id" => 1,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "unresolved",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 18,
                "email" => "test18@militarycars.com",
                "specialist_id" => 5,
                "task_id" => 2,
                "year" => "2026",
                "division_id" => 2,
                "model_id" => 2,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "in_progress",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 19,
                "email" => "test19@militarycars.com",
                "specialist_id" => 5,
                "task_id" => 3,
                "year" => "2026",
                "division_id" => 3,
                "model_id" => 3,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "escalated",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 20,
                "email" => "test20@militarycars.com",
                "specialist_id" => 5,
                "task_id" => 4,
                "year" => "2026",
                "division_id" => 4,
                "model_id" => 4,
                "misc" => "4x4",
                "info_type" => "customer",
                "info_number" => "9102691234",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "completed",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 21,
                "email" => "test21@militarycars.com",
                "specialist_id" => 6,
                "task_id" => 1,
                "year" => "2026",
                "division_id" => 1,
                "model_id" => 1,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "unresolved",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 22,
                "email" => "test22@militarycars.com",
                "specialist_id" => 6,
                "task_id" => 2,
                "year" => "2026",
                "division_id" => 2,
                "model_id" => 2,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "in_progress",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 23,
                "email" => "test23@militarycars.com",
                "specialist_id" => 6,
                "task_id" => 3,
                "year" => "2026",
                "division_id" => 3,
                "model_id" => 3,
                "misc" => "4x4",
                "info_type" => "fo",
                "info_number" => "123456",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "escalated",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 24,
                "email" => "test24@militarycars.com",
                "specialist_id" => 6,
                "task_id" => 4,
                "year" => "2026",
                "division_id" => 4,
                "model_id" => 4,
                "misc" => "4x4",
                "info_type" => "customer",
                "info_number" => "9102691234",
                "details" => "this is a test ticket, please help me",
                "attachments" => json_encode([]),
                "status" => "completed",
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
